# -*- coding: utf-8 -*-
"""Raliways

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ezCwOwHsB5spCUxoMYOzgOzuHN3CE11I
"""

import geemap,geemap as import_map
import ee

ee.Authenticate()
ee.Initialize(project='mshruti724')
map=import_map.Map()

vector_layer = ee.FeatureCollection("projects/mshruti724/assets/Raliway")

Map = geemap.Map()

Map.addLayer(vector_layer, {}, 'Raliways Goa')

Map